# This workflow will install Python dependencies and run Flask-specific tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Flask Application Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_flask:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test Flask application
      run: |
        export FLASK_APP=app.py
        export FLASK_ENV=development
        pytest
